## helm
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: pgbouncer
    namespace: default
    chart: ../pgbouncer
    values:
    - users:
        pgbouncer: md5bc3eb42ff2e374313252d5f9b8a023fa
      databases:
        postgres:
          host: postgresql
          port: 5432
          dbname: postgres
          auth_user: pgbouncer

  - name: postgresql
    namespace: default
    chart: bitnami/postgresql
    values:
      - resources:
          requests:
            cpu: "1000m"
            memory: "1Gi"